version: '2.2'
services:
    config-server:
        container_name: config-server
        build:
            context: ./MicroserviceConfigServer
            dockerfile: Dockerfile-configserver
        image: config-server:latest
        expose:
            - 9090
        ports:
            - 9090:9090
        networks:
            - emp-network
        volumes:
            - config-repo:/var/lib/config-repo
    eureka-server:
        container_name: eureka-server
        build:
            context: ./EmployeeEurekaServer
            dockerfile: Dockerfile-EurekaServer
        image: eureka-server:latest
        expose:
            - 9091
        ports:
            - 9091:9091
        networks:
            - emp-network
    EmployeeSearchService:
        container_name: EmployeeSearch
        build:
            context: ./EmployeeSearchService
            dockerfile: Dockerfile-EmployeeSearch
        image: employeesearch:latest
        environment:
            - spring.cloud.config.uri=http://config-server:9090
            - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka/
        entrypoint: /home/bin/EmployeeSearch-entrypoint.sh
        expose:
            - 8080
        ports:
            - 8080:8080
        networks:
            - emp-network
        links:
            - config-server:config-server
            - eureka-server:eureka-server
        depends_on:
            - config-server
            - eureka-server
        logging:
            driver: json-file
    EmployeeDashboardService:
        container_name: EmployeeDashboard
        build:
            context: ./EmployeeDashboardService
            dockerfile: Dockerfile-EmployeeDashboard
        image: employeedashboard:latest
        environment:
            - spring.cloud.config.uri=http://config-server:9090
            - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka/
        entrypoint: /home/bin/EmployeeDashBoard-entrypoint.sh
        expose:
            - 8081
        ports:
            - 8081:8081
        networks:
            - emp-network
        links:
            - config-server:config-server
            - eureka-server:eureka-server
        depends_on:
            - config-server
            - eureka-server
        logging:
            driver: json-file
    ZuulServer:
        container_name: ZuulServer
        build:
            context: ./EmployeeZuulService
            dockerfile: Dockerfile-ZuulServer
        image: zuulserver:latest
        environment:
            - spring.cloud.config.uri=http://config-server:9090
            - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka/
        entrypoint: /home/bin/EmployeeZuul-entrypoint.sh
        expose:
            - 8084
        ports:
            - 8084:8084
        networks:
            - emp-network
        links:
            - config-server:config-server
            - eureka-server:eureka-server
        depends_on:
            - config-server
            - eureka-server
        logging:
            driver: json-file
networks:
    emp-network:
        driver: bridge
volumes:
    config-repo:
        external: true